terrain_attributes:
  - name: elevation
    sigmas: [0]
  - name: slope
    sigmas: [1, 3, 5]
  - name: slope_break_index
    sigmas: [1, 3, 5]
  - name: profile_curvature
    sigmas: [1, 3, 5]
  - name: planform_curvature
    sigmas: [1, 3, 5]
  - name: mean_curvature
    sigmas: [1, 3, 5]

zonal_stats:
  window_sizes: [3, 5, 7]
  stats: ["std","range"]
  apply_to:
    elevation:
      sigmas: [0]
    slope:
      sigmas: [1]
    slope_break_index:
      sigmas: [1]
    profile_curvature:
      sigmas: [1]
    planform_curvature:
      sigmas: [1]
    mean_curvature:
      sigmas: [1]
